### ISSUE TITLE
herokuのデプロイに関して

### ISSUE THREAD

**Issue by misogihagi** [hi1280/mean-example#1]
`git clone git://github.com/hi1280/mean-example.git`
`cd mean-example`
依存性解決のスクリプト
`sed s/3.7.2/3.7.1/ package-lock.json > package-lock.json`
`sed -e '2995d' package-lock.json > package-lock.json`
`sed -e 's/"rxjs": "^6.0.0"/"rxjs": "6.3.3"/' package.json  > tmp`
`cp tmp package.json `
`rm tmp`
`npm install psl node-sass`
`npm install`

`heroku create`
`git add .`
`git commit -am "dependency solve"`
`git push heroku master`
`heroku logs`

上記のようにサンプルをherokuにデプロイすると

このようなメッセージがでます。

Build succeeded
Starting process with command `npm start`

> mean-example@0.0.0 prestart /app
> npm run build

> mean-example@0.0.0 build /app
> ng build --prod

sh: 1: ng: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! mean-example@0.0.0 build: `ng build --prod`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the mean-example@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /app/.npm/_logs/2019-09-03T06_13_47_342Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mean-example@0.0.0 prestart: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mean-example@0.0.0 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /app/.npm/_logs/2019-09-03T06_13_47_361Z-debug.log
State changed from starting to crashed
State changed from crashed to starting
Process exited with status 1

これは何が原因でしょうか。

**Comment by hi1280** [comment]
いつのまにかherokuの仕様が変更になったようで、package.jsonを変える必要がありました。
angular cliをdependenciesに含めないといけないなど。
詳しくは下記に書かれてます。
https://devcenter.heroku.com/articles/mean-apps-restful-api

package.jsonを修正したので改めて試してもらえますか。

**Comment by misogihagi** [comment]
動くようになりました！
ありがとうございます！
